### ISSUE TITLE
Method POST not supported in batch operations

### ISSUE THREAD

**Issue by lukesoft** [danielsaidi/parse-net#1]

**Comment by danielsaidi** [comment]
Hi!

When I received an e-mail regarding this issue, it contained a pretty thorough description of the problem you were facing. Any ideas why the description is empty here?

Anyhow, I have not used Parse.NET for posting or putting objects to Parse. I guess that their developer forums would be a better place to ask about the error messages in their API.

Best of luck

**Comment by lukesoft** [comment]
Oh sorry.....Its blank because I tried to delete the issue because i had posted on the wrong project...I meant to raise that issue with parse-csharp project. Thanks
